MODEL:
  NAME: "attn"
  FREEZE_BN: True
  NUM_CLASSES: 2
DATASETS:
  SOURCE_TRAIN: "polyp_train"
  TARGET_TRAIN: "bli_train"
  TEST: "polyp_val"
  CROSS_VAL: 0
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: [512, 512]
  # PIXEL_MEAN: [103.939, 116.779, 123.68]
  # PIXEL_MEAN: [104.00698793, 116.66876762, 122.67891434]
  # PIXEL_STD: [1., 1., 1.]
  # TO_BGR255: True
AUG:
  NAME: "attn"
  BLUR_PROB: 0.7
  ROTATE_PROB: 0.7
  JITTER_PROB: 0.7
  FLIP_PROB: 0.7
  PROB: 0.7
  COLLATE: "attn"
SOLVER:
  BASE_LR: 1e-3
  WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 20
  EPOCHS: 100
  CHECKPOINT_PERIOD: 5
TEST:
  BATCH_SIZE: 1