MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  NUM_CLASSES: 19
DATASETS:
  SOURCE_TRAIN: "gta5_train"
  TEST: "cityscapes_val"
  CROSS_VAL: 0
# INPUT:
  # PIXEL_MEAN: [103.939, 116.779, 123.68]
  # PIXEL_MEAN: [104.00698793, 116.66876762, 122.67891434]
  # PIXEL_STD: [1., 1., 1.]
  # TO_BGR255: True
SOLVER:
  BASE_LR: 5e-4
  BATCH_SIZE: 8
  EPOCHS: 100
  CHECKPOINT_PERIOD: 5
TEST: 
  BATCH_SIZE: 1