MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  NUM_CLASSES: 2
DATASETS:
  SOURCE_TRAIN: "kvasir_train"
  TEST: "kvasir_val"
  CROSS_VAL: 0
INPUT:
  INPUT_SIZE_TEST: [1024, 512]
  # PIXEL_MEAN: [103.939, 116.779, 123.68]
  # PIXEL_MEAN: [104.00698793, 116.66876762, 122.67891434]
  # PIXEL_STD: [1., 1., 1.]
  # TO_BGR255: True
SOLVER:
  BASE_LR: 5e-4
  BATCH_SIZE: 12
  EPOCHS: 100
  CHECKPOINT_PERIOD: 5
TEST:
  BATCH_SIZE: 1