MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  NUM_CLASSES: 19
DATASETS:
  DATASET_DIR: "/home/admin_mcn/taint/dataset"
  SOURCE_TRAIN: "gta5_train"
  TEST: "gta5_val"
  CROSS_VAL: 0
# INPUT:
  # PIXEL_MEAN: [103.939, 116.779, 123.68]
  # PIXEL_MEAN: [104.00698793, 116.66876762, 122.67891434]
  # PIXEL_STD: [1., 1., 1.]
  # TO_BGR255: True
AUG:
  NAME: "gald"
  COLLATE: None
SOLVER:
  BASE_LR: 0.0001
  BATCH_SIZE: 6
  EPOCHS: 10
  CHECKPOINT_PERIOD: 2
TEST: 
  BATCH_SIZE: 1